In [251]:
from pytrends.request import TrendReq
from datetime import datetime as dt
import datetime

pytrends_daily = TrendReq(hl='en-US', tz=360)
pytrends_weekly = TrendReq(hl='en-US', tz=360)

In [252]:
#Parameters
#Week starts on Sunday
#Start and end must be within 90 days for daily data

start = '2022-01-02'
end = '2022-04-03'
kw_list = ['bitcoin','ethereum']


end_dt = dt.strptime(end,"%Y-%m-%d")
end_dt_last_yr = dt(end_dt.year - 1, end_dt.month,end_dt.day)
end_last_yr = end_dt_last_yr.strftime("%Y-%m-%d")

tf_daily = start +' '+ end
tf_weekly = end_last_yr + ' ' + end

In [253]:
pytrends_daily.build_payload(kw_list,cat=0,timeframe = tf_daily)
daily_data = pytrends_daily.interest_over_time()
daily_data = daily_data[kw_list]
#daily_data

In [254]:
pytrends_weekly.build_payload(kw_list,cat=0,timeframe = tf_weekly)
weekly_data = pytrends_weekly.interest_over_time()
weekly_data = weekly_data[kw_list]
#weekly_data

In [255]:
for kw in kw_list:
    daily_data[kw + '_wk'] = 0

In [256]:
for index_daily in daily_data.index:
    for index_weekly in weekly_data.index:
        if (index_daily == index_weekly):
            for i in range(7):
                try:
                    daily_data.loc[index_daily]['bitcoin_wk'] = weekly_data.loc[index_daily]['bitcoin']
                    daily_data.loc[index_daily]['ethereum_wk'] = weekly_data.loc[index_daily]['ethereum']
                except:
                    pass

In [258]:
daily_data['BTC SVI Adj Factor'] = daily_data['bitcoin_wk']/daily_data['bitcoin']
daily_data['ETH SVI Adj Factor'] = daily_data['ethereum_wk']/daily_data['ethereum']

In [259]:
daily_data.head(50)

            bitcoin  ethereum  ...  BTC SVI Adj Factor  ETH SVI Adj Factor
date                           ...
2022-01-02       38         9  ...            0.947368            1.000000
2022-01-03       41        10  ...            0.000000            0.000000
2022-01-04       40        10  ...            0.000000            0.000000
2022-01-05       44        10  ...            0.000000            0.000000
2022-01-06       66        13  ...            0.000000            0.000000
2022-01-07       65        14  ...            0.000000            0.000000
2022-01-08       57        12  ...            0.000000            0.000000
2022-01-09       51        12  ...            0.705882            0.750000
2022-01-10       56        11  ...            0.000000            0.000000
2022-01-11       54        11  ...            0.000000            0.000000
2022-01-12       50        11  ...            0.000000            0.000000
2022-01-13       46        11  ...            0.000000            0.000000
2022-01-14       44        10  ...            0.000000            0.000000
2022-01-15       38         9  ...            0.000000            0.000000
2022-01-16       38         9  ...            1.026316            1.111111
2022-01-17       40         9  ...            0.000000            0.000000
2022-01-18       43         9  ...            0.000000            0.000000
2022-01-19       40         9  ...            0.000000            0.000000
2022-01-20       41        10  ...            0.000000            0.000000
2022-01-21       80        14  ...            0.000000            0.000000
2022-01-22      100        17  ...            0.000000            0.000000
2022-01-23       74        14  ...            0.675676            0.785714
2022-01-24       96        18  ...            0.000000            0.000000
2022-01-25       73        13  ...            0.000000            0.000000
2022-01-26       68        13  ...            0.000000            0.000000
2022-01-27       61        11  ...            0.000000            0.000000
2022-01-28       57        11  ...            0.000000            0.000000
2022-01-29       48        10  ...            0.000000            0.000000
2022-01-30       45        10  ...            0.800000            0.900000
2022-01-31       48        10  ...            0.000000            0.000000
2022-02-01       49        11  ...            0.000000            0.000000
2022-02-02       47        10  ...            0.000000            0.000000
2022-02-03       48        10  ...            0.000000            0.000000
2022-02-04       50        11  ...            0.000000            0.000000
2022-02-05       53        12  ...            0.000000            0.000000
2022-02-06       43        10  ...            0.813953            0.800000
2022-02-07       55        12  ...            0.000000            0.000000
2022-02-08       51        10  ...            0.000000            0.000000
2022-02-09       51        10  ...            0.000000            0.000000
2022-02-10       49        10  ...            0.000000            0.000000
2022-02-11       44         9  ...            0.000000            0.000000
2022-02-12       40         9  ...            0.000000            0.000000
2022-02-13       36         8  ...            0.833333            0.875000
2022-02-14       42         8  ...            0.000000            0.000000
2022-02-15       43         9  ...            0.000000            0.000000
2022-02-16       40         8  ...            0.000000            0.000000
2022-02-17       42         8  ...            0.000000            0.000000
2022-02-18       43         8  ...            0.000000            0.000000
2022-02-19       38         8  ...            0.000000            0.000000
2022-02-20       43         9  ...            0.906977            0.888889

[50 rows x 6 columns]

In [188]:
for i in range(5):
    print(i)

0
1
2
3
4

In [190]:
daily_data.head(10)

            bitcoin  ethereum  ...  BTC SVI Adj Factor  ETH SVI Adj Factor
date                           ...
2022-01-02       38         9  ...            0.973684                1.00
2022-01-03       41        10  ...            0.000000                0.00
2022-01-04       40        10  ...            0.000000                0.00
2022-01-05       44        10  ...            0.000000                0.00
2022-01-06       66        13  ...            0.000000                0.00
2022-01-07       65        14  ...            0.000000                0.00
2022-01-08       57        12  ...            0.000000                0.00
2022-01-09       51        12  ...            0.705882                0.75
2022-01-10       56        11  ...            0.000000                0.00
2022-01-11       54        11  ...            0.000000                0.00

[10 rows x 6 columns]